obj-$(CONFIG_STICKERNEL)		+= devfreq_boost.o
obj-$(CONFIG_STICKERNEL)	+= wireguard.o
obj-$(CONFIG_STICKERNEL)	+= zswap.o
obj-$(CONFIG_STICKERNEL)	+= klapse.o
obj-$(CONFIG_STICKERNEL)	+= cpu_input_boost.o
